version: 0.2
phases:
  install:
    commands:
      - whoami
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.20.4/2021-04-12/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
      - kubectl version --short --client
      - mkdir ~/.kube
      - aws sts get-caller-identity
      - aws eks update-kubeconfig --name eksworkshop-eksctl --region ap-northeast-2 
      - kubectl get po
      - kubectl get nodes
  pre_build:
    commands:
      - echo Pre Build started on `date`
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - kubectl apply -f ./bookinfo.yaml
